dds_correction_form_data = {
    "header_fax": "678-413-8479",
    "defendant_lastname": "MAGALLANES",
    "defendant_firstname": "EMILY",
    "defendant_middlename": "VANESSA",
    "defendant_dob": "06/23/1960",
    "defendant_license_state": "GA",
    "defendant_license_no": "C8459357",
    "court_name": "Court Name Here",
    "court_phone": "+1  (558)  928-6543",
    "court_citation": "681535",
    "court_charge": "Charge description here",
    "court_ocga": "40-13-32",
    "court_disposition_date": "01/25/2020",
    "court_violation_date": "12/04/2019",
    "court_disposition": "Nolo Contendere",
    "change_text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "change_reason_within90": False,
    "change_reason_within180": True,
    "change_reason_clerical": False,
    "change_court_official": "Nemo Robin",
    "change_title_official": "Nevaeh Charla",
}
