order_and_sentence_data = {
    "order_date": "07/16/2019",
    "defendant_name": "JUAN URIEL MELENDEZ HERRERA",
    "citations": [
        {
            "citation_number": "E31415",
            "offense_number": "40-6-48",
            "offense_description": "FAILURE TO MAINTAIN LANE-1ST",
            "disposition": "Pled Guilty",
            "balance": 0.00,
        },
        {
            "citation_number": "E31416",
            "offense_number": "40-5-20",
            "offense_description": "DRIVING WITHOUT A VALID LICENSE-1ST",
            "disposition": "Pled Guilty",
            "balance": 99990.00,
        },
        {
            "citation_number": "E31417",
            "offense_number": "40-6-391a",
            "offense_description": "DUI-ALCOHOL-LESS SAFE-1ST",
            "disposition": "Pled Guilty",
            "balance": 0.00,
        },
        {
            "citation_number": "E62869",
            "offense_number": "18-11",
            "offense_description": "PUBLIC INTOXICATION AND PUBLIC CONSUMPTION-1ST",
            "disposition": "Pled Guilty",
            "balance": 0.00,
        },
        {
            "citation_number": "E62870",
            "offense_number": "40-6-92",
            "offense_description": "CROSSING ROADWAY ELSEWHERE THAN AT CROSSWALK",
            "disposition": "Pled Guilty",
            "balance": 0.00,
        }
    ],
    "total_amount": "0.00",
    "bonds_received": "1,780.00",
    "sentence_length": "120",
    "sentence_period": "months",
    "house_eligible_length": "15",
    "house_eligible_period": "days",
    "house_length": "180",
    "house_period": "days",
    "jail_immediate": True,
    "jail_date": "10/22/2020",
    "jail_time": "02:55 PM",
    "11": True,
    "11_amount": "532.58",
    "11_party": "Hubert Blaine Wolfeschlegelsteinhausenbergerdorff",
    "12": False,
    "13": True,
    "14": False,
    "15": True,
    "16": False,
    "16_meetings": "12",
    "16_sessions": "16",
    "17": True,
    "17_length": "15",
    "17_period": "hours",
    "18": False,
    "18_hours": "90",
    "19": True,
    "19_days": "30",
    "20": False,
    "20_months": "3",
    "21": True,
    "21_months": "2",
    "22": False,
    "22_months": "6",
    "22_amount": "300.34",
    "23": True,
    "23_months": "7",
    "24": False,
    "25": True,
    "25_description": "other condition description",
}
