fdo_data = {
    "defendant_name": "John Doe",
    "case_number": "12313242",
    "citations": [
        {
            "citation_number": "1231234423",
            "violation": "111-1: TEST VIOLATION",
        },
        {
            "citation_number": "213242345",
            "violation": "222-2: TEST VIOLATION 2",
        },
    ],
    "term": "TERM",
    "original_sentence": True,
    "modified_sentence": False,
    "revocation_sentence": False,
    "plea": True,
    "in_person": False,
    "by_mail": False,
    "negotiated": False,
    "non_negotiated": False,
    "guilty": True,
    "non_contest": False,
    "trial_verdict": False,
    "guilty_on_citations": True,
    "guilty_on_citation_numbers": ["12234524", "32454353", "654456546"],
    "non_guilty_on_citations": True,
    "non_guilty_on_citation_numbers": ["23324234", "1231231"],
    "other_disposition": True,
    "nolle_prosequi_order_on_citations": ["12313141", "3454575"],
    "defendant_filed_bond_forfeiture_form": True,
    "defendant_filed_acknowledgment_of_waiver_of_rights_form": False,
    "citation_table": [  # citation table can have more than 4 entries
        {
            "citation_number": "1223253",
            "disposition": "Guilty",
            "length_of_sentence": "30 days",
            "computation_of_sentence": "Concurrent",
            "fine": 50.00,
            "community_service_hours": "24",
            "restitution": "TEST",
        },
        {
            "citation_number": "324342",
            "disposition": "Contest",
            "length_of_sentence": "60 days",
            "computation_of_sentence": "Probation",
            "fine": 100.00,
            "community_service_hours": "48",
            "restitution": "TEST 2",
        },
    ],
    "1": True,
    "2": True,
    "2_order_date": "12/12/2019",
    "3": True,
    "3_month": "3",
    "4": True,
    "4_month": "4",
    "4_suspended": True,
    "4_terminated": False,
    "5": True,
    "5_day": "5",
    "5_probation": True,
    "5_suspended": False,
    "5_terminated": False,
    "pay_to_court": False,
    "pay_to_probation": False,
    "pay_to_victim": True,
    "victims": [
        {
            "victim_name": "John Smith",
            "victim_address": "123 TEST AVE, CHICAGO, IL, 60000",
            "amount": 50.00,
        },
        {
            "victim_name": "Mike Smith",
            "victim_address": "321 TEST AVE, CHICAGO, IL, 60000",
            "amount": 100.00,
        },
    ],
    "stay_away": True,
    "stay_away_victims": ["John Smith", "Mike Smith"],
    "not_return": True,
    "not_return_address": "123 TEST AVE, CHICAGO, IL, 60000",
    "not_commit": True,
    "pay_fine": True,
    "complete_service": True,
    "other": True,
    "other_text": "TEST",
    "shall_appear": True,
    "shall_appear_date": "10/10/2019",
    "defendant_represented_by_self": True,
    "defendant_represented_by_attorney": False,
    "order_date": "09/06/2019",
    "judge_is_phinia_aten": False,  #
    "judge_other": True,  # One of the two is checked
    "judge_other_name": "John Smith",
}

advisement_acknowledgement_waiver_plea_data = {
    "defendant_name": "John Doe",
    "case_number": "231344112",
    "citation_numbers": ["1231331", "234535435", "45345345435"],
    "defendant_education": "College",
    "defendant_DOB": "04/01/1990",
    "defendant_english": True,  # True for "I can both speak and read English", False for "I cannot speak or read English"
    "interpreter_language": "Spanish",
    "citation_table": [  # Citation list can have more than 3 entries
        {
            "citation_number": "1231234423",
            "violation": "111-1: TEST VIOLATION",
            "plea": True,  # True for "GUILTY", False for "NO CONTEST"
        },
        {
            "citation_number": "213242345",
            "violation": "222-2: TEST VIOLATION 2",
            "plea": False,
        },
    ],
    "ordered_date": "09/06/2019",
    "judge_is_phinia_aten": False,  #
    "judge_other": True,  # One of the two is checked
    "judge_other_name": "John Smith",
}
